# Generated by Django 5.0.1 on 2024-01-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kutubxona',
            new_name='Kutubxonachi',
        ),
    ]
