# Generated by Django 5.0.1 on 2024-01-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0002_rename_kutubxona_kutubxonachi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='qaytarish_soni',
        ),
        migrations.AddField(
            model_name='record',
            name='qaytarish_sana',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
