# Generated by Django 5.0.1 on 2024-01-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0003_remove_record_qaytarish_soni_record_qaytarish_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kutubxonachi',
            name='ish_vaqti',
            field=models.CharField(choices=[('8:00 dan 17:00 gacha', '8:00 dan 17:00 gacha'), ('10:00 dan 21:00 gacha', '10:00 dan 21:00 gacha')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='qaytarish_sana',
            field=models.DateField(),
        ),
    ]
