# Generated by Django 5.0.1 on 2024-01-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0005_alter_kutubxonachi_ish_vaqti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kutubxonachi',
            name='ish_vaqti',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kutubxonachi',
            name='ism',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
